Item.create!(title: 'Buy milk', content: 'Buy milk', color: 'purple')
Item.create!(title: 'Buy cookies', content: 'Buy Oreos', color: 'purple')
Item.create!(title: 'Clean bathroon', content: 'Clean the shower', color: 'pink')
Item.create!(title: 'Dust', content: 'Clean the living room', color: 'pink')
Item.create!(title: 'Call Directv', content: 'Cancel showtime', color: 'blue')
Item.create!(title: 'Learn Backbone.js', content: 'Learn Backbone', color: 'blue')
